name: Java DitaMap Processor

on:
  push:
    branches:
      - Main
  pull_request:
    branches:
      - Main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17.0.11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17.0.11'

    - name: Compile Java code
      run: |
        javac -d out java code for merging in runner 1/DitaMapProcessor.java

    - name: Run Java program
      run: |
        java -cp out DitaMapProcessor
      env:
        INPUT_FILE_PATH: "Maps/Region/ass/countries/angola/content-types/directory.ditamap"
        OUTPUT_FILE_PATH: "output.dita"

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-dita
        path: output.dita
