name: Java DitaMap Processor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Compile Java code
      run: |
        javac -d out src/**/*.java

    - name: Run Java program
      run: |
        java -cp out DitaMapProcessor
      env:
        INPUT_FILE_PATH: "Maps/Region/ass/countries/angola/content-types/directory.ditamap"
        OUTPUT_FILE_PATH: "output.dita"

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-dita
        path: output.dita
